// data.jsx
const MOCK = {
  user: {
    name: 'Claire Dubois',
    initial: 'CD',
    email: 'claire.dubois@exemple.fr',
    phone: '+33 6 12 34 56 78',
    company: 'Studio Hélium',
    memberSince: 'Janvier 2025',
    plan: 'Membre +',
  },
  stats: {
    active: 2,
    hoursBooked: 48,
    completed: 12,
    savings: 124,
    memberPoints: 340,
    nextReward: 500,
  },
  upcoming: [
    {
      id: 'b1',
      space: 'Salle Verrière',
      spaceKey: 'verriere',
      date: 'Mardi 22 avril',
      dateShort: 'Mar 22',
      time: '09:00 – 12:00',
      duration: '3h',
      people: 4,
      price: 72,
      status: 'confirmed',
      payment: 'paid',
      day: 22, month: 'avril',
    },
    {
      id: 'b2',
      space: 'Open-space',
      spaceKey: 'open',
      date: 'Jeudi 24 avril',
      dateShort: 'Jeu 24',
      time: '14:00 – 18:00',
      duration: '4h',
      people: 1,
      price: 36,
      status: 'pending',
      payment: 'pending',
      day: 24, month: 'avril',
    },
    {
      id: 'b3',
      space: 'Salle Étage',
      spaceKey: 'etage',
      date: 'Lundi 28 avril',
      dateShort: 'Lun 28',
      time: '10:00 – 12:00',
      duration: '2h',
      people: 6,
      price: 60,
      status: 'confirmed',
      payment: 'paid',
      day: 28, month: 'avril',
    },
  ],
  past: [
    { id: 'p1', space: 'Open-space', spaceKey: 'open', date: 'Ven 18 avril', time: '09:00 – 17:00', people: 1, price: 45, status: 'completed' },
    { id: 'p2', space: 'Salle Verrière', spaceKey: 'verriere', date: 'Mar 15 avril', time: '14:00 – 16:00', people: 3, price: 48, status: 'completed' },
    { id: 'p3', space: 'Événementiel', spaceKey: 'event', date: 'Sam 12 avril', time: '18:00 – 23:00', people: 12, price: 240, status: 'completed' },
  ],
  spaces: {
    open: { label: 'Open-space', color: '#417972', bg: 'rgba(65,121,114,0.12)' },
    verriere: { label: 'Salle Verrière', color: '#5A938B', bg: 'rgba(90,147,139,0.14)' },
    etage: { label: 'Salle Étage', color: '#8A6B1F', bg: 'rgba(242,211,129,0.22)' },
    event: { label: 'Événementiel', color: '#C0534C', bg: 'rgba(192,83,76,0.1)' },
  },
  promos: [
    { id: 1, title: 'Happy Hour', body: '-20% sur les open-space après 17h', color: '#F2D381' },
    { id: 2, title: 'Privatisation weekend', body: 'Tarif dégressif dès 4h', color: '#5A938B' },
  ],
};
window.MOCK = MOCK;
